version: '3.8'

services:

  nginx:
    image: 'bitnami/nginx:latest'
    depends_on:
      - phpfpm
    networks:
      - app-tier
    ports:
    # httpのポートを80番と、httpsのポートを443番に設定
      - '80:80'
      - '443:443'
    volumes:
    # nginxが起動していない場合、パスが間違っている可能性がある。
    # ここは、ホスト側の設定ファイルが、nginxの中の指定された場所に設定ファイルがコピーされる。
    # この時、nginx側のファイルはどこでも置いていいわけではない
      - ./docker/nginx/default.conf:/opt/bitnami/nginx/conf/server_blocks/default.conf

  # php:
  # Dockerfileを指定
  #   build: ./docker/php
  #   volumes:
  #     - ./src:/var/www/

  phpfpm:
    image: 'bitnami/php-fpm:latest'
    networks:
      - app-tier
    volumes:
    # URLのパスから.phpファイルのアクセスを可能にするために、ホスト側のファイルをコンテナ側にマウントする
      - ./src:/app

  mysql:
    image: mysql:8.0.26
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    networks:
      - app-tier
    command:
      mysqld --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: pass
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge